name: "prepare-image"
description: "prepare-image"
inputs:
  zip-image-path:
    type: string

runs:
  using: composite
  steps:
    - name: prepare image
      shell: bash
      run: |

        ## Get an image ##
        wget ${{ inputs.zip-image-path }}

        # xz -d *img.xz               
        unzip *lite.zip

        mv *img raspios.img

        ## Install required packages ## 
        sudo apt-get update && sudo apt-get install -y qemu-utils qemu-user-static

        ## Load nbd kernel module ##
        sudo modprobe nbd max_part=8

        ## Connect the image to nbd ##
        sudo qemu-nbd --connect=/dev/nbd0 --format=raw raspios.img

        ## Mount the image partition ##
        sudo mount /dev/nbd0p2 /mnt

        ## Update
        sudo chroot /mnt apt-get update
        sudo ls
