name: Modify Raspberry Pi OS Image

on:
  push: # Запуск действия при каждом пуше в репозиторий
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testus
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: prepare-image
        uses: ./.github/actions/prepare-image
        with:
          zip-image-path: "https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz"

      - name: set-time-zone
        uses: ./.github/actions/set-time-zone
        with:
          time-zone: Asia/Sakhalin

      - name: config-user
        uses: ./.github/actions/config-user
        with:
          username: ${{ secrets.DEF_USERNAME }}
          password: ${{ secrets.DEF_PASSWORD }}

      - name: config-ssh
        uses: ./.github/actions/config-ssh

      - name: plug-scripts
        uses: ./.github/actions/plug-scripts

      - name: config-access-point
        uses: ./.github/actions/config-access-point

      - name: zip-image
        uses: ./.github/actions/zip-image

      - name: deploy img.xz
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release'}}
        with:
          files: raspios.img.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
